// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKf3JXonwQoBrKDYytcZxUT591Xf0x7w',
    appId: '1:357836312212:web:baf2f215c567b3f827ae81',
    messagingSenderId: '357836312212',
    projectId: 'fchat-1c5b0',
    authDomain: 'fchat-1c5b0.firebaseapp.com',
    storageBucket: 'fchat-1c5b0.appspot.com',
    measurementId: 'G-QZD4N1L815',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9LcAITdpV1ekirhJ9x2-njvBFy2676Y',
    appId: '1:357836312212:android:7d8be9a5c2da112327ae81',
    messagingSenderId: '357836312212',
    projectId: 'fchat-1c5b0',
    storageBucket: 'fchat-1c5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkglTZo4XGteXsjvS0xLsDZORR4osdVY',
    appId: '1:357836312212:ios:2f7e666a28f3148827ae81',
    messagingSenderId: '357836312212',
    projectId: 'fchat-1c5b0',
    storageBucket: 'fchat-1c5b0.appspot.com',
    iosBundleId: 'com.example.fchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrkglTZo4XGteXsjvS0xLsDZORR4osdVY',
    appId: '1:357836312212:ios:9d0ffa209fa0f00027ae81',
    messagingSenderId: '357836312212',
    projectId: 'fchat-1c5b0',
    storageBucket: 'fchat-1c5b0.appspot.com',
    iosBundleId: 'com.example.fchat.RunnerTests',
  );
}
